tasks:
  - init: bash ./deploy_handlers/gitpod.sh

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 8090
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - oderwat.indent-rainbow
    - usernamehw.errorlens
    - eamodio.gitlens
    - discloud.discloud