services:
  - type: web
    name: disnake_music
    env: python
    plan: free
    repo: https://github.com/zRitsu/disnake-LL-music-bot.git
    buildCommand: pip3 install -r requirements.txt --no-cache-dir
    startCommand: python3 main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: DEFAULT_PREFIX
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: MONGO
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: AUTO_DOWNLOAD_LAVALINK_SERVERLIST
        value: true
      - key: MONGO_SSL_FIX
        value: true
    autoDeploy: false # optional
